import { NextResponse } from "next/server";

const MOCK_PRODUCTS = [
  // --- CAKES (5 items) ---
  {
    id: "cake-1",
    name: "Red Velvet Wedding Cake",
    description: "A stunning 3-tier red velvet cake with smooth cream cheese frosting.",
    category: "Cakes",
    price: 300000,
    image: "/images/cakes/cake-1.jpg",
    stock: 5,
    featured: true,
  },
  {
    id: "cake-2",
    name: "Custom Birthday Drip Cake",
    description: "Moist vanilla sponge layered with rich chocolate ganache.",
    category: "Cakes",
    price: 100000,
    image: "/images/cakes/cake-2.jpg",
    stock: 10,
    featured: true,
  },
  {
    id: "cake-3",
    name: "Classic Chocolate Fudge Cake",
    description: "Decadent, rich chocolate cake with multiple layers of fudge.",
    category: "Cakes",
    price:80000,
    image: "/images/cakes/cake-3.jpg",
    stock: 8,
    featured: false,
  },
  {
    id: "cake-4",
    name: "Assorted Cupcakes Box (12pcs)",
    description: "A beautiful box of 12 mini cupcakes in assorted flavors.",
    category: "Cakes",
    price: 30000,
    image: "/images/cakes/cake-4.jpg",
    stock: 20,
    featured: false,
  },
  {
    id: "cake-5",
    name: "Fruit & Cream Celebration Cake",
    description: "Light vanilla sponge filled with fresh seasonal fruits.",
    category: "Cakes",
    price: 60000,
    image: "/images/cakes/cake-5.jpg",
    stock: 7,
    featured: false,
  },

  // --- PASTRIES (5 items) ---
  {
    id: "pastry-1",
    name: "Classic Nigerian Meat Pie",
    description: "Flaky, buttery pastry crust filled with seasoned minced meat.",
    category: "Pastries",
    price: 1500,
    image: "/images/pastries/pastry-1.jpg",
    stock: 50,
    featured: true,
  },
  {
    id: "pastry-2",
    name: "Savory Chicken Pie",
    description: "Golden-brown pastry filled with tender shredded chicken.",
    category: "Pastries",
    price: 2000,
    image: "/images/pastries/pastry-2.jpg",
    stock: 45,
    featured: true,
  },
  {
    id: "pastry-3",
    name: "Jumbo Sausage Roll",
    description: "Flaky pastry wrapped around a juicy, well-seasoned sausage.",
    category: "Pastries",
    price: 1500,
    image: "/images/pastries/pastry-3.jpg",
    stock: 60,
    featured: false,
  },
  {
    id: "pastry-4",
    name: "Glazed Doughnuts (Pack of 4)",
    description: "Soft, fluffy, and freshly fried doughnuts with sugar glaze.",
    category: "Pastries",
    price: 3000,
    image: "/images/pastries/pastry-4.jpg",
    stock: 30,
    featured: false,
  },
//   {
//     id: "pastry-5",
//     name: "Butter Croissant",
//     description: "Authentic French-style butter croissant, baked to perfection.",
//     category: "Pastries",
//     price: 1500,
//     image: "/images/pastries/pastry-5.jpg",
//     stock: 25,
//     featured: false,
//   },

  // --- SMALL CHOPS (5 items) ---
  {
    id: "smallchops-1",
    name: "Premium Small Chops Platter",
    description: "A mix of puff-puff, samosas, spring rolls, and chicken wings.",
    category: "Small Chops",
    price: 25000,
    image: "/images/small-chops/platter-1.jpg",
    stock: 20,
    featured: true,
  },
  {
    id: "smallchops-2",
    name: "Spicy Chicken Wings (6pcs)",
    description: "Crispy fried chicken wings tossed in our signature spicy sauce.",
    category: "Small Chops",
    price: 20000,
    image: "/images/small-chops/wings.jpg",
    stock: 30,
    featured: false,
  },
  {
    id: "smallchops-3",
    name: "Vegetable Spring Rolls (5pcs)",
    description: "Crunchy rolls filled with fresh mixed vegetables.",
    category: "Small Chops",
    price: 2500,
    image: "/images/small-chops/spring-rolls.jpg",
    stock: 40,
    featured: false,
  },
  {
    id: "smallchops-4",
    name: "Beef Samosas (5pcs)",
    description: "Triangular pastries filled with spiced minced beef.",
    category: "Small Chops",
    price: 2500,
    image: "/images/small-chops/samosas.jpg",
    stock: 40,
    featured: false,
  },
  {
    id: "smallchops-5",
    name: "Mini Burgers Slider Pack",
    description: "Five bite-sized beef burgers perfect for party trays.",
    category: "Small Chops",
    price: 15000,
    image: "/images/small-chops/sliders.jpg",
    stock: 15,
    featured: false,
  },

  // --- MEALS (5 items) ---
  {
    id: "meals-1",
    name: "Special Jollof Rice & Chicken",
    description: "Smoky party jollof rice served with grilled chicken and plantain.",
    category: "Meals",
    price: 5000,
    image: "/images/meals/jollof.jpg",
    stock: 25,
    featured: true,
  },
  {
    id: "meals-2",
    name: "Fried Rice & Beef Stew",
    description: "Colorful fried rice loaded with veggies and tender beef chunks.",
    category: "Meals",
    price: 7000,
    image: "/images/meals/fried-rice.jpg",
    stock: 25,
    featured: true,
  },
//   {
//     id: "meals-3",
//     name: "Creamy Pasta Alfredo",
//     description: "Penne pasta in a rich creamy white sauce with chicken strips.",
//     category: "Meals",
//     price: 10000,
//     image: "/images/meals/pasta.jpg",
//     stock: 20,
//     featured: false,
//   },
  {
    id: "meals-4",
    name: "Ofada Rice & Ayamase Sauce",
    description: "Local unpolished rice served with spicy green pepper stew.",
    category: "Meals",
    price: 10000,
    image: "/images/meals/ofada.jpg",
    stock: 15,
    featured: false,
  },
  {
    id: "meals-5",
    name: "Swallow Combo (Pounded Yam)",
    description: "Smooth pounded yam served with choice of Egusi or Efo Riro soup.",
    category: "Meals",
    price: 5000,
    image: "/images/meals/swallow.jpg",
    stock: 15,
    featured: false,
  },

  // --- DESSERTS (5 items) ---
//   {
//     id: "dessert-1",
//     name: "Fresh Fruit Salad Bowl",
//     description: "A refreshing mix of seasonal fruits with honey drizzle.",
//     category: "Desserts",
//     price: 2500,
//     image: "/images/desserts/fruit-salad.jpg",
//     stock: 20,
//     featured: true,
//   },
//   {
//     id: "dessert-2",
//     name: "Chocolate Brownie Sundae",
//     description: "Warm brownie topped with vanilla ice cream and chocolate syrup.",
//     category: "Desserts",
//     price: 3000,
//     image: "/images/desserts/brownie.jpg",
//     stock: 15,
//     featured: false,
//   },
//   {
//     id: "dessert-3",
//     name: "Cheesecake Slice",
//     description: "Creamy New York style cheesecake with berry compote.",
//     category: "Desserts",
//     price: 2800,
//     image: "/images/desserts/cheesecake.jpg",
//     stock: 10,
//     featured: false,
//   },
  {
    id: "dessert-4",
    name: "Chin Chin (Sweet Crunch)",
    description: "Traditional crunchy sweet snack, perfect for munching.",
    category: "Desserts",
    price: 2500,
    image: "/images/desserts/chinchin.jpg",
    stock: 50,
    featured: false,
  },
//   {
//     id: "dessert-5",
//     name: "Vanilla Ice Cream Scoop",
//     description: "Premium creamy vanilla ice cream.",
//     category: "Desserts",
//     price: 1500,
//     image: "/images/desserts/icecream.jpg",
//     stock: 30,
//     featured: false,
//   },

  // --- DRINKS (5 items) ---
//   {
//     id: "drinks-1",
//     name: "Zobo Drink (1 Liter)",
//     description: "Chilled hibiscus drink infused with ginger and pineapple.",
//     category: "Drinks",
//     price: 2000,
//     image: "/images/drinks/zobo.jpg",
//     stock: 20,
//     featured: true,
//   },
//   {
//     id: "drinks-2",
//     name: "Fresh Pineapple Juice",
//     description: "100% natural freshly squeezed pineapple juice.",
//     category: "Drinks",
//     price: 2500,
//     image: "/images/drinks/pineapple.jpg",
//     stock: 15,
//     featured: true,
//   },
//   {
//     id: "drinks-3",
//     name: "Chapman Cocktail",
//     description: "Classic Nigerian cocktail with Fanta, Sprite, and grenadine.",
//     category: "Drinks",
//     price: 3000,
//     image: "/images/drinks/chapman.jpg",
//     stock: 10,
//     featured: false,
//   },
//   {
//     id: "drinks-4",
//     name: "Iced Coffee Latte",
//     description: "Strong espresso blended with milk and served over ice.",
//     category: "Drinks",
//     price: 2500,
//     image: "/images/drinks/coffee.jpg",
//     stock: 20,
//     featured: false,
//   },
//   {
//     id: "drinks-5",
//     name: "Bottled Water (Large)",
//     description: "75cl chilled bottled water.",
//     category: "Drinks",
//     price: 500,
//     image: "/images/drinks/water.jpg",
//     stock: 100,
//     featured: false,
//   },

  // --- CATERING SERVICES (5 items) ---
  {
    id: "catering-1",
    name: "Small Chops Party Platter",
    description: "Premium platter of puff-puff, samosas, and spring rolls.",
    category: "Catering Services",
    price: 25000,
    image: "/images/catering/catering-1.jpg",
    stock: 15,
    featured: true,
  },
  {
    id: "catering-2",
    name: "Corporate Event Buffet",
    description: "Full-service buffet catering including proteins and carbs.",
    category: "Catering Services",
    price: 300000,
    image: "/images/catering/catering-2.jpg",
    stock: 10,
    featured: true,
  },
//   {
//     id: "catering-3",
//     name: "Wedding Cocktail Package",
//     description: "Elegant cocktail hour service with gourmet canapés.",
//     category: "Catering Services",
//     price: 150000,
//     image: "/images/catering/catering-3.jpg",
//     stock: 5,
//     featured: true,
//   },
  {
    id: "catering-4",
    name: "Birthday Party Catering",
    description: "Complete solution including small chops and main course.",
    category: "Catering Services",
    price: 300000,
    image: "/images/catering/catering-4.jpg",
    stock: 8,
    featured: false,
  },
  {
    id: "catering-5",
    name: "Church Program Refreshment",
    description: "Affordable refreshment packs with pastry and water.",
    category: "Catering Services",
    price: 3000,
    image: "/images/catering/catering-5.jpg",
    stock: 100,
    featured: false,
  },
];

export async function POST() {
  try {
    // Simulate network delay
    await new Promise((resolve) => setTimeout(resolve, 500));
    return NextResponse.json(MOCK_PRODUCTS);
  } catch (error) {
    console.error("Error generating products:", error);
    return NextResponse.json({ error: "Failed" }, { status: 500 });
  }
}